plenty_mark: 800250

furnace_mark: 800251
#下面这个是附魔需要消耗的钻币
points_on_enchant: 200


#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------

