plenty_mark: 800250

furnace_mark: 800251
#下面这个是附魔需要消耗的钻币
points_on_enchant: 200
#下面这个是升级效率附魔不同阶段消耗的钻币
point_on_efficiency:
  phase1: 5
  phase2: 10
  phase3: 20
  phase4: 30
  phase5: 50



#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------

