name: SoulEnchants
version: '${project.version}'
main: starshine.soulenchants.SoulEnchants
api-version: '1.16'

commands:
  soulenchants:
    description: "This is the command of the plugin"
    aliases: [ soe ]
    permission: SoulEnchants.Main
  soulenchantsfix:
    description: "This is the fixed command of the plugin"
    aliases: [ soefix ]



softdepend: [PlayerPoints]